### ISSUE TITLE
XEP-0363: HTTP File Upload

### ISSUE THREAD

**Issue by weijibin** [qxmpp-project/qxmpp#129]
Does QXMPP support XEP-0363?  what can i do for it ?

**Comment by LNJ2** [comment]
[Kaidan](https://git.kaidan.im/kaidan/kaidan) will be switching to QXmpp in the next weeks/months, we will definitely also need HTTP File Upload, so if nobody else will implement it, I'd do it. :)

**Comment by LNJ2** [comment]
I started to implement it, you can track the progress here:
`<ads>`https://git.kaidan.im/kaidan/kaidan/commits/feature/qxmpp-rewrite `</ads>`

As soon as it is finished, I'll create a pull request here.

**Comment by LNJ2** [comment]
Base is working (stanza extensions, requesting/receiving upload slot).

I just don't know exactly how to parse and write the additional error types, they are embedded into the normal error. I could just parse them, but my problem is I can't write them to XML again since the error tag would then either be written twice or I would need to edit the ` QXmppStanza::Error ` (that might be an option; QXmppMessage is also just edited for every new XEP).
https://xmpp.org/extensions/xep-0363.html#errors

Before I do something that makes no sense or would not be accepted, I'd like to ask you what to do here.

**Comment by lnjX** [comment]
What's still missing:
- [x] request/slot IQs (https://github.com/qxmpp-project/qxmpp/commit/9c8fea86564712aca4363bb1ebe5fd227eff188f)
- [ ] error cases (#203)
- [ ] upload request manager (#203)
- [ ] upload manager (for actually uploading files)
