### ISSUE TITLE
Build error with 'undefined reference to QXmppSaslDigestMd5::parseMessage'

### ISSUE THREAD

**Issue by xdien** [qxmpp-project/qxmpp#149]
Build failed with steps:

> cmake -G "MinGW Makefiles" .
mingw32-make

Error lines:
>[ 71%] Linking CXX executable tst_qxmppsasl.exe
CMakeFiles\tst_qxmppsasl.dir/objects.a(tst_qxmppsasl.cpp.obj):tst_qxmppsasl.cpp:
(.text+0x25): undefined reference to `QXmppSaslDigestMd5::parseMessage(QByteArra
y const&)'
CMakeFiles\tst_qxmppsasl.dir/objects.a(tst_qxmppsasl.cpp.obj):tst_qxmppsasl.cpp:
(.text+0xa2): undefined reference to `QXmppSaslDigestMd5::serializeMessage(QMap<
QByteArray, QByteArray> const&)'....

Build info:
>Windows 7 64bit
mingw32-make 5.3.0
cmake 3.10.2
Qt 5.7.0

Has anyone ever been like this?

**Comment by jlaine** [comment]
@olesalscheider I think the problem here is that QXMPP_AUTOTEST_EXPORT is no longer being defined since the switch to CMake. QXMPP_AUTOTEST_EXPORT is used for symbols which don't need to be exported for a normal build, but *do* need to be exported to link the unit tests.

It's the equivalent of Qt's Q_AUTOTEST_EXPORT, see:
https://wiki.qt.io/Qt_Autotest_Environment

**Comment by jlaine** [comment]
I have set up an appveyor config which reproduces the problem:

https://ci.appveyor.com/project/jlaine/qxmpp
