### ISSUE TITLE
make install: directory doc/html doesn't exist

### ISSUE THREAD

**Issue by poxip** [qxmpp-project/qxmpp#27]
This happens after executing `make install`, if I create doc/html directory (`mkdir doc/html`) everythings goes fine.
```
make[2]: Entering directory '/home/poxip/qxmpp/examples/example_9_vCard'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/poxip/qxmpp/examples/example_9_vCard'
make[1]: Leaving directory '/home/poxip/qxmpp/examples'
cd doc/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/poxip/qxmpp/doc/doc.pro -o Makefile ) && make -f Makefile install
make[1]: Entering directory '/home/poxip/qxmpp/doc'
make[1]: Nothing to be done for 'install'.
make[1]: Leaving directory '/home/poxip/qxmpp/doc'
cp -f -R /home/poxip/qxmpp/doc/html /usr/local/share/doc/qxmpp/
cp: cannot stat ‘/home/poxip/qxmpp/doc/html’: No such file or directory
Makefile:356: recipe for target 'install_htmldocs' failed
make: [install_htmldocs] Error 1 (ignored)
```

**Comment by jlaine** [comment]
You are right, if "make docs" has not been invoked, the HTML documentation has not been generated and cannot be install.

This used not to be an issue as the distribution tarballs always included the HTML documentation, but this is no longer the case since the move to github. I don't think we should require generating the HTML docs, as this requires having doxygen installed, which might not be practical on all platforms.

A quick fix would be to stop installing the HTML docs and leave this up to packagers, but this means notifying them.

**Comment by jlaine** [comment]
OK in the end : the HTML documentation is only built / installed if QXMPP_USE_DOXYGEN=1 is passed to qmake
