### ISSUE TITLE
Provide QXmpp prebuilt packages for Qt5

### ISSUE THREAD

**Issue by poxip** [qxmpp-project/qxmpp#29]
For instance http://packages.ubuntu.com/source/vivid/qxmpp QXmpp package requires Qt4 (and is built with Qt4, so this might cause and causes some crashes, etc). and that'd be nice to be able to install QXmpp from apt, yum, etc but for Qt5, not 4. I suggest naming like `qxmpp-qt5` or something similar (and of course. same for pkgconfig).

**Comment by 0xd34df00d** [comment]
I doubt this is actually an upstream issue.

**Comment by jlaine** [comment]
We unfortunately do not have the manpower to provide pre-built binaries.

**Comment by vityafx** [comment]
Just tried to instantiate QXmppClient and it crashes with Qt 5.3.1 just with one line:
`QXmppClient c;`
Of course project is linked to qxmpp, and etc. Test many times on fresh projects to figure out where is the problem exactly.

**Comment by jlaine** [comment]
Ubuntu indeed ships qxmpp compiled for qt4. If you want to use qt5 you will need to compile qxmpp yourself, you cannot use a library compiled against qt4 in a program linked against qt5 (this is causing your crash)

**Comment by vityafx** [comment]
I think I can provide a qt5 package but only in my ppa of course while your packages are in main repository. Did not try to be a Debian unstable repository maintainer yet, but ppa for a long time.

**Comment by RHamidR** [comment]
@vityafx did you solve the problem with use QXMPP lib in Qt5?
Can you show me a step-by-step way to do it?.
i can't even include this library in Qt Creator. I have no idea. Please help me.

Thanks in advance.

**Comment by jlaine** [comment]
The problems was clearly mixing qt4/qt5

**Comment by vityafx** [comment]
@RHamidR Simply compile it by yourself. No need to use qtcreator:

    qmake
    make
    sudo make install

**Comment by vityafx** [comment]
I am trying to build qxmpp in my ppa and it fails on i386 however it builds successfully on amd64. Can you guys please take a look what is wrong on i386 build?

[i386 log](https://launchpadlibrarian.net/195927277/buildlog_ubuntu-utopic-i386.qxmpp_0.8.2-4_FAILEDTOBUILD.txt.gz)

[amd64 log](https://launchpadlibrarian.net/195927285/buildlog_ubuntu-utopic-amd64.qxmpp_0.8.2-4_UPLOADING.txt.gz)

**Comment by chris179** [comment]
From a short look I see that the html directory is missing:
> cp: cannot stat 'debian/tmp/usr/share/doc/qxmpp/html/': No such file or directory

There was a change - you should have a look at issue 27

**Comment by vityafx** [comment]
Hm, How did it work in amd64 build then? Also I can't build it on both amd64 and i386 with `QXMPP_USE_DOXYGEN=1`:

[i386 log](https://launchpadlibrarian.net/195934452/buildlog_ubuntu-utopic-amd64.qxmpp_0.8.2-5_FAILEDTOBUILD.txt.gz)
[amd64 log](https://launchpadlibrarian.net/195934462/buildlog_ubuntu-utopic-i386.qxmpp_0.8.2-5_FAILEDTOBUILD.txt.gz)

**Comment by RHamidR** [comment]
dear @vityafx , thanks for your answer.

i didn't want to ask these foolish questions here again but i didn't find any good tutorial about compile and use projects like this. I'm sure that i was wrong in my searches about your answer last 3 days ago and i know the issue is not clear to me.

If you direct me some more detailed guide links on the internet about how to build the (Cpp or Qt) library for cross-platform programming and how to use this built library in Qt5 i will be very grateful and I'll try to Learn and read more (if i have some resources) and I will not ask these kind of questions here.

Thanks in advance

**Comment by vityafx** [comment]
@RHamidR Please, ask your question on http://stackverflow.com and you'll get help asap. Explain problems you have, your goals and what you want to achieve.

Now I can only point you to project's README because it has all the steps to build the library on any unix machine. I know nothing about windows(visual studio) programming and compiling so in that case I can't help you well.

Therefore, ask a question on the resource and let people help you and others who have your problems too. Good luck!

**Comment by RHamidR** [comment]
Thank you @vityafx.
Please at least tell me what is this ways name and (people calls this what). search and ask what?

Static build? Cross-platform build? Dynamic build? Build using Qt? or MinGW? 
Just a little more help for my search and asking question.

Because i asked much questions about this and in most of case just achieved down vote with no help in stackoverflow.
thank you

**Comment by vityafx** [comment]
@RHamidR Well, it depends on what you want to achieve. Take a look at [SSCCE](http://sscce.org/). Read it, realize and go.

Where and when do you have problems? During compilation? Then post compilation log, compilation commands/etc and everything what did you do in order to reproduce the error you have, this also makes other people understand your problem and give you most elegant solution. 

For example:

I can't compile Qt/C++ [qxmpp](https://github.com/qxmpp-project) library on windows. I have **X** error during compilation:

    cd qxmpp/src
    qmake
    make
    
    Compiler: **X**

If viewers will need any more information they'll simply ask you to give it to them. Don't forget about **SSCCE** !

**Comment by RHamidR** [comment]
I don't know. maybe its better to don't try for cross-platform programming and start my project on eclipse.
I compile the project by "Run" button in Qt Creator With "Desktop Qt 5.4.0.MinGW 32bit" Kit and everything is OK. in the build directory it gives me some files include "qxmpp_d0.dll" and i know it is dynamic library and is for Windows.
But when i "Run" the project while the selected "Kit" is "Android for armeabi (GCC 4.9 , Qt 5.4.0)" it shows error and i know this project can act with Android because many people told me that and this is my mistake in building.

So this is the full explanation of my problem..
I cant use the QXMPP.

I have to Search and ask for "Static library building"? or another thing?
WHAT IS THE FIRST STEP?

Dear @vityafx thanks for SSCCE article suggestion, I will read and act by that instruction.


And i am sorry for asking these questions in misplace.

**Comment by vityafx** [comment]
@RHamidR You should fully explain your problem and situation. I don't understand what you do with the library and what for.

**Comment by RHamidR** [comment]
I have QXMPP library and Qt 5.4 for android and I don't know What to do.
I want to use this library to develop and provide a cross-platform instant message application for our website clients.
I am a .net programmer, It's just my first try in Qt and these things.
and my problem is how to include and use this library classes and APIs on Qt for android and windows.

what is "qmake"
what is "make"
what is "sudo make install"

Please direct me to a link that shows me how to build and use this project on windows for my purpose.

Thanks so much.

**Comment by RHamidR** [comment]
Thank you @vityafx and all guys here.
I was lost in past for adding this lib to my projects because i didn't know how to do it (add headers and cpp files? use the library after buildation? or another way?) and that was because i am beginner in Qt and I have bad English to explain what is really going on in my head.
But finally i did it by editing my projects ".pro" file with these commands and it worked:

    CONFIG(debug, debug|release) {
        win32{
            QXMPP_LIBRARY_NAME_INC = qxmpp_d0
        } else {
            QXMPP_LIBRARY_NAME_INC = qxmpp_d
        }
    }else{
        win32{
            QXMPP_LIBRARY_NAME_INC = qxmpp0
        }else{
            QXMPP_LIBRARY_NAME_INC = qxmpp
        }
    }
    LIBS += -L./qxmpp/src -l$$QXMPP_LIBRARY_NAME_INC

I have new issue [here](https://github.com/qxmpp-project/qxmpp/issues/39) and i need your help and please be patient with me.
Thanks all of you.
