### ISSUE TITLE
Omemo v1 vs. v2

### ISSUE THREAD

**Issue by geobra** [qxmpp-project/qxmpp#515]
Hi

Given the fact that this project made a huge progress the last years with great features, we tried to port Shmoose away from Swiften and also use qxmpp.

During this, we discovered that the current omemo implementation in qxmpp is 'v2 only' which in turn has the side effect that it is currently not compatible with all the other major xmpp clients.

Do you have a plan how to handle this? There are e.g. omemo pyhton implementations available which handles both, v1 and v2 of the omemo protocol transparent to the using product. 

Best regards
Geobra

**Comment by melvo** [comment]
@geobra Great to hear that you consider switching to QXmpp :) We will work on several other features in the coming months (including message replies and more support for A/V calls). There is no plan for supporting older OMEMO versions because that would need resources we want to use for new XEPs. In addition, there are already other clients supporting OMEMO 2 or working on it.

**Comment by melvo** [comment]
Is [ShmoNG](/geobra/shmong) the corresponding repository?

**Comment by geobra** [comment]
Thank you for the information. Yes, https://github.com/geobra/shmong is the 'new' refactored xmpp client which should be based on qxmpp. @ron282 just tries to figure out what modifications are needed to get both omemo versions running by use of qxmpp.

**Comment by melvo** [comment]
@geobra @ron282 Cool :) Good luck!
