### ISSUE TITLE
Phone number parsing in vCards

### ISSUE THREAD

**Issue by towe75** [qxmpp-project/qxmpp#65]
Hi,

it seems like there is a bug in QXmpp's vCard parser. Instead of looking for a "TEL" element (like stated in RFC2426) it searches for some "PHONE" element. Hence the phones() list is always empty. I'm connecting to a OpenFire server and i did a trace of the traffic. I can see "TEL" elements but no "PHONE" elements.

Thanks.

**Comment by servonic** [comment]
I would agree that this is a bug in qxmpp.
XEP-0054 (IMHO that is more relevant than RFC 2426 in this case) also specifies TEL and not PHONE.

I use qxmpp as a server library and just did a quick hack to test the other direction. I added phone numbers to my vcards. (As expected) Pidgin did not show thelphone numbers until i changed qxmpp to write "TEL" instead of "PHONE" in QXmppVCardIq.cpp

**Comment by towe75** [comment]
Ok, good to know. I also checked the vcard parser in the smack library. Again only TEL is used, no reference to PHONE whatsoever.
