### ISSUE TITLE
QXmppServer seems not to handle </stream:stream>

### ISSUE THREAD

**Issue by servonic** [qxmpp-project/qxmpp#70]
It seems that the qxmpp server ignores the receipt of closing &lt;/stream:stream> tags.

I've implemented an XMPP server using qxmpp. 
If a client wants to close the connection, he sends a &lt;/stream:stream> and then waits for the closing stream-tag by the server (as described in http://tools.ietf.org/html/rfc6120#section-4.4 point 1). If the client ignores point 3 and waits infinite for the closing tag (or has defined the "reasonable amount of time" to be more than 2 minutes) the server does not send the closing tag before running into a timeout after 120 seconds.

If the client did not send an unavailable presence prior to its &lt;/stream:stream> it seems still available and I didn't find a possibility in my server code to create the missing unavailable presence as the signal clientDisconnected is not raised until the timeout occurs.

Did I just miss to implement something or is this something that needed to be fixed inside qxmpp?

**Comment by jlaine** [comment]
You are correct, and the behaviour you describe applies both to QXmpp based clients and servers. I have made a change to QXmppStream so that the end of the incoming stream triggers closing the outgoing stream. Can you please confirm this fixes your issue?

Re-reading the RFC brings to mind another issue: to be fully compliant with the RFC we should not close the TCP socket until the incoming stream has been closed. However I am reluctant to make this change at this point as I fear it will potentially cause regressions in the form of "hung" connections.

**Comment by servonic** [comment]
Thank you for the fix - you were too fast, I already was preparing a pull request...
Your solution looks similar to my approach, however I'm going to test it this afternoon and leave a reply.

I agree with your concern regarding the TCP socket: For instance (if my observations are correct) the client library jabber-net has a bug and doesn't close the TCP connection after receiving the closed strem.

**Comment by servonic** [comment]
The test was successful. 
(The jabber-net based client keeps a connection in state CLOSE_WAIT, but this is a problem of jabber-net and not qxmpp.)

**Comment by jlaine** [comment]
Good news!
