### ISSUE TITLE
Handle IQ responses properly with QFutures

### ISSUE THREAD

**Issue by LightZam** [qxmpp-project/qxmpp#96]
I have a problem about sending an iq.

for example,

```
QXmppMucRoom *room = client->mucManager().rooms().value(0);
room->setConfiguration(form);
```

there is no possible way to know setConfiguration(form)'s result, 

because iq's id was hidden from user who use the lib in this situation, and QxmppMucRoom didn't catch the result for user. so there is no way to know setConfiguration works or not.

is it a design issue in this case?

how to get result from iq if i need to know?

**Comment by jlaine** [comment]
The API could indeed be improved here. However, having the user deal directly with sending / receiving the IQs kind of defeats the whole "manager" concept. Any suggestions?

**Comment by LightZam** [comment]
how about using lambda or promise to handle sendPacket ?
it might help a lot when deal with receiving every iq's result.

**Comment by lnjX** [comment]
I thought of something like this (not sure whether everything)
```cpp
class QXmppClient {
    QSharedPointer<QXmppIqResult> sendIq(QXmppIq iq);
}
class QXmppClientPrivate {
    QVector<QSharedPointer<QXmppIqResult>> pendingIqResults;
}

class QXmppIqResult {
    enum TransmissionError {
        Disconnected, // disconnectFromServer() called, before result could arrive
        SocketFailure // IQ was sent although socket was not connected or did not send the full data (see  https://github.com/qxmpp-project/qxmpp/blob/master/src/base/QXmppStream.cpp#L132-L138 )
    };

signals:
    void replyReceived(QDomElement element);
    void errorReceived(QXmppIq iq);
    void transmissionFailed(TransmissionError error)

public:
    void resendIq(); // resend same request, but with a new ID (not sure if that is really needed)
}
```

It would also be nice to get a feedback, when a `<message/>` was really sent / acknowledged via stream management.

**Comment by 0xd34df00d** [comment]
I'd vote for `QFuture`-based API. It just composes a bit better with other primitives that might be out there for working with and chaining futures (or at least my codebase does have those :)).

**Comment by lnjX** [comment]
How would I create a QFuture? Obviously `QtConcurrent::run()` is not what we want. I found something about `QFutureInterface`, but I can't find any documentation for it.

**Comment by 0xd34df00d** [comment]
Indeed, you've found the right thing! `QFutureInterface` is the way to go, but it's really not documented. The API turns out to be stable though — the things I wrote quite a few years ago circa Qt 4.7 are still working without a single change with Qt 5.14.

So, long story short, you create a `QFutureInterface<T> iface;`, return `iface.future()` to the caller, call `iface.reportStarted()` when the corresponding task starts executing (or just call that straight away), and then call `iface.reportFinished()` once it's done.

**Comment by lnjX** [comment]
> the things I wrote quite a few years ago circa Qt 4.7 are still working without a single change with Qt 5.14.

The question is: do we need to rebuild QXmpp everytime Qt is updated then? Those are probably private headers and so this could lead to problems with the ABI compatibility...

Maybe `std::future` from C++11 is also an option?

**Comment by 0xd34df00d** [comment]
I keep missing notifications about this thread for some reason, sorry.

> The question is: do we need to rebuild QXmpp everytime Qt is updated then?

I cannot really prove it, but seems like we don't.

> Those are probably private headers and so this could lead to problems with the ABI compatibility...

They are indeed, but they are leaking anyway via QtConcurrent, and looking at the way they leak (QtConcurrentRun → `qtconcurrentstoredfunctioncall.h` → `qtconcurrentrunbase.h` being one example) I tend to think Qt _must_ preserve ABI compatibility for this particular private header as long as it tries to be ABI-compatible wrt the QtConcurrent module.

> Maybe std::future from C++11 is also an option?

Uh, `std::future` was largely a mistake (I cannot google a good paper about that I've seen a few years ago though because of all the `future_error` documentation in google search results). What's particularly relevant for this use case — it does not have a `then`-like method, so there is no way to get a notification or invoke a function once it completes (unless the user wants to do something with condvars themselves, which I doubt they do).

**Comment by lnjX** [comment]
Qt 6 will ship [QPromise](https://doc-snapshots.qt.io/qt6-dev/qpromise.html) which is properly documented and is going to be the "official" way to create custom QFutures. I'd like to use it, but it obviously requires Qt 6 :/
